### ISSUE TITLE
lilydev-debian-vm-0.3 has Italian keyboard layout as default

### ISSUE THREAD

**Issue by karlinhigh** [fedelibre/LilyDev#2]
There was a reference to changing keyboard layouts in setup instructions:

http://lilypond.org/doc/v2.19/Documentation/contributor/lilydev#installing-lilydev-in-virtualbox

But it said the default layout is American English.

**Comment by fedelibre** [comment]
Thanks for the report!

I'm not sure what happened; perhaps an autosetup from my locale. I'll be careful for the next release.

I also have a patch for the Contributor Guide, which is currently out-of-date. But I first want to see if I manage to run GUB successfully in LilyDev eventually.

**Comment by fedelibre** [comment]
I'm investigating...

When I build the container I see there's an interactive dialog which we should avoid:

```
Setting up keyboard-configuration (1.164) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debc
onf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Configuring keyboard-configuration
----------------------------------

Please select the layout matching the keyboard for this machine.

  1. English (US)
  2. English (US) - Cherokee
  3. English (US) - English (Colemak)
  4. English (US) - English (Dvorak alternative international no dead keys)
  5. English (US) - English (Dvorak)
  6. English (US) - English (Dvorak, international with dead keys)
  7. English (US) - English (Macintosh)
  8. English (US) - English (Programmer Dvorak)
  9. English (US) - English (US, alternative international)
  10. English (US) - English (US, international with dead keys)
  11. English (US) - English (US, with euro on 5)
  12. English (US) - English (Workman)
  13. English (US) - English (Workman, international with dead keys)
  14. English (US) - English (classic Dvorak)
  15. English (US) - English (international AltGr dead keys)
  16. English (US) - English (left handed Dvorak)
  17. English (US) - English (right handed Dvorak)
  18. English (US) - English (the divide/multiply keys toggle the layout)
  19. English (US) - Russian (US, phonetic)
  20. English (US) - Serbo-Croatian (US)
  21. Other
```

Probably the vm image has the same issue and I guess it defaults to current LANG if no input is provided within a certain time.

**Comment by fedelibre** [comment]
The interactive dialog is another issue...

I've built a new image using mkosi from master and the issue seems solved, as default keyboard layout is indeed English (US):

![LilyDev-keyboard-layout](https://user-images.githubusercontent.com/1644647/70022900-0fa57200-1596-11ea-8f93-ac2524458bc8.png)
