### ISSUE TITLE
v3 releases don't contain a VM image 

### ISSUE THREAD

**Issue by 2-0** [fedelibre/LilyDev#38]
Hi @fedelibre, 

While setting up LilyDev I found that the latest release V3 doesn't contain `LilyDev-VERSION-debian-vm.zip` file: [LilyDev releases](https://github.com/fedelibre/LilyDev/releases/tag/v3).  Is this setup still the recommended way to set up the environment? If so, is the V2 sufficiently different? 

Thanks!

**Comment by fedelibre** [comment]
Yes, because it's a big file and it took days to upload it to GitHub so I gave up.
The VM image was useful only for Windows/Mac users.

I'm not maintaining this repo anymore. I think there are now better ways to set up a LilyPond development environment.
